// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pcgngpfkgkpqrljgekzq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBjZ25ncGZrZ2twcXJsamdla3pxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU2MDM4OTUsImV4cCI6MjA3MTE3OTg5NX0.uqrkLKvhX5tPx_rdnTMFLSwymlFxWOFSyzH8YiI40Os";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);